import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";

import "../../app/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "ecommerce app",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
