import type { Metadata } from "next";

import {
  ClerkProvider
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton
} from "@clerk/nextjs";

import "../../app/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "ecommerce app",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
