import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import { SanityLive } from "@/sanity/lib/live";

import Header from "@/components/Header";

// visual editing and model editing
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

import "../../app/globals.css";
import { DisableDraftMode } from "@/components/DisableDraftMode";

export const metadata: Metadata = {
  title: "ecommerce app",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {(await draftMode()).isEnabled && (
            <>
              <VisualEditing />
              <DisableDraftMode />
            </>
          )}
          <main>
            <Header />
            {children}
          </main>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
