import type { Metadata } from "next";
import ProductsView from "@/components/ProductsView";
import { getAllCategories } from "@/sanity/lib/products/getAllCategories";
import { getAllProducts } from "@/sanity/lib/products/getAllProducts";
import BlackFridayBanner from "./BlackFridayBanner";
import { Product } from "@/sanity.types";

export const dynamic = "force-dynamic";
export const revalidate = 3600;

export const metadata: Metadata = {
  title: "ecommerce app",
  description: "Generated by create next app"
};

export default async function Home() {
  const products: Product[] = await getAllProducts();
  const categories = await getAllCategories();
  return (
    <div className="pt-2 bg-gray-100">
      {/* banner */}
      <BlackFridayBanner />
      {/* render all products */}
      <div>
        <div className="max-w-7xl mx-auto flex flex-col items-center min-h-screen p-4">
          <ProductsView products={products} categories={categories} />
        </div>
      </div>
    </div>
  );
}
